// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "meta": {
    "description": "Open-Source-Workshopplanung. Selbst gehostet, MCP-fähig.",
    "printTitle": "Druckansicht"
  }
};
export default messages;