import { readdirSync, readFileSync, statSync } from 'node:fs'
import { join, relative, sep } from 'node:path'
import { describe, expect, it } from 'vitest'

/**
 * How long a module may get before it has to be split.
 *
 * Not a style rule. A module nobody can hold in their head is where the next
 * bug hides, and it gets that way one honest addition at a time -- every single
 * one of them too small to be the moment somebody stops and splits the file.
 * So the budget says the moment out loud, and says it while the split is still
 * an afternoon rather than a project.
 *
 * The number is descriptive, not aspirational: it is roughly where this
 * codebase's modules already sit, so it fails for the files that grew past
 * their subject and stays quiet for the rest. Tests are not counted -- a long
 * test file is a well-covered subject, not a design problem.
 *
 * When it fails, split the module. Raising the budget is the one repair that
 * does not repair anything.
 */
const BUDGET = 500

/**
 * Modules that may be long, each with the reason.
 *
 * The list is the point: an exemption somebody has to write a sentence for is
 * an exemption somebody thinks about. Adding a file here without a reason that
 * survives being read aloud is how a budget stops meaning anything.
 */
const EXEMPT: Record<string, string> = {
  'server/db/schema.ts':
    'One Drizzle declaration per table, and the tables reference each other both ways ' +
    '(workshop <-> workshop_day, module <-> cluster). Split along any line and the imports ' +
    'become circular; split along none and it is a list, which is what a schema is.',
  'messages/de.d.json.ts':
    'Generated by next-intl from de.json. In the repository because tsc reads the allowed ' +
    'translation keys out of it -- see CLAUDE.md -- but nothing is written here by hand.',
}

describe('a source module', () => {
  const root = join(__dirname)

  const sources = (dir: string): string[] =>
    readdirSync(dir).flatMap((entry) => {
      const path = join(dir, entry)
      if (statSync(path).isDirectory()) return sources(path)
      return /\.tsx?$/.test(entry) && !/\.test\.tsx?$/.test(entry) ? [path] : []
    })

  /** Posix, so the exemptions read the same on every machine. */
  const name = (path: string) => relative(root, path).split(sep).join('/')

  const lengths = sources(root).map((path) => ({
    name: name(path),
    lines: readFileSync(path, 'utf8').split('\n').length,
  }))

  it('stays inside its budget, or is exempt with a reason', () => {
    const over = lengths
      .filter(({ name, lines }) => lines > BUDGET && EXEMPT[name] === undefined)
      .sort((a, b) => b.lines - a.lines)
      .map(({ name, lines }) => `${name}: ${lines} lines`)
    expect(over).toEqual([])
  })

  /**
   * An exemption for a file that has been split, renamed or deleted is a note
   * about the past pretending to be a rule.
   */
  it('is not exempt for a reason that has gone away', () => {
    const stale = Object.keys(EXEMPT).filter(
      (name) => !lengths.some((file) => file.name === name && file.lines > BUDGET),
    )
    expect(stale).toEqual([])
  })

  /** A guard that matches nothing guards nothing. */
  it('is found at all', () => {
    expect(lengths.length).toBeGreaterThan(100)
  })
})
